name: "Tinc VPN Client"
description: "Open-source VPN daemon"
url: https://github.com/curzon01/hassio-tinc-vpn-client
version: "0.0.3"
slug: "tinc"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
options:
  server_name: server01
  server_public_key: paste-server-public-key-base64
  connect_to: tinc-server-fqdn-or-ip
  connect_port: 655
  server_subnet: 10.0.0.1/32
  client_name: client01
  public_key: paste-client-public-key-base64
  private_key: paste-client-private-key-base64
  client_subnet: 10.0.0.2/32
  client_route: 10.0.0.0/24
  address_family: ipv4
schema:
  server_name: str
  server_public_key: str
  connect_to: str
  connect_port: str
  server_subnet: str
  client_name: str
  public_key: str
  private_key: str
  client_subnet: str
  client_route: str
  address_family: list(ipv4|ipv6)
